// Action Types

// Actions: Songlist
export const INIT_SEARCH = 'INIT_SEARCH';
export const SET_SONGLIST = 'SET_SONGLIST';
export const SET_SONGTRACKS_FOR_SONG_IN_SONGLIST = 'SET_SONGTRACKS_FOR_SONG_IN_SONGLIST';

// Actions: Playlist
export const INIT_PLAYLIST = 'INIT_PLAYLIST';
export const DOWNLOAD_PLAYLIST = 'DOWNLOAD_PLAYLIST';
export const ADD_SONGTRACK_TO_PLAYLIST = 'ADD_SONGTRACK_TO_PLAYLIST';
export const REMOVE_SONGTRACK_FROM_PLAYLIST = 'REMOVE_SONGTRACK_FROM_PLAYLIST';

// Actions: Playlist - editable
export const EDIT_TITLE_FOR_PLAYLIST = 'EDIT_TITLE_FOR_PLAYLIST';
export const EDIT_NOTE_FOR_SONG_IN_PLAYLIST = 'EDIT_NOTE_FOR_SONG_IN_PLAYLIST';
